// JavaScript source code

var infojuegosaccion = '[{"titulo":"FAR CRY 5", "imagen":"covers_juegos/accion/farcry5.jpg", "title":"Imagen-de-Far-Cry-5", "fondo":"img1", "descripcion":"Far Cry 5 es un videojuego de acción-aventura en primera persona desarrollado por Ubisoft Montreal y publicado por Ubisoft para PlayStation 4, Xbox One y Microsoft Windows. Es la undécima entrega de la serie Far Cry. Su lanzamiento se produjo el 27 de marzo de 2018. Fecha de estreno inicial: 27 de marzo de 2018. Motor: Dunia Engine. Modos de juego: Un jugador; Multijugador. Distribuidor: Ubisoft. Desarrolladores: Ubisoft Reflections, Ubisoft Kiev, Ubisoft Montreal, Ubisoft Shanghai, Ubisoft Toronto, Red Storm.", "comprar":"comprar_juegos/comprar_farcry5.html"},' +
                        '{"titulo":"GTA V", "imagen":"covers_juegos/accion/gta5.jpg", "title":"Imagen-de-GTA-V", "fondo":"img2", "descripcion":"Grand Theft Auto V es un videojuego de acción-aventura de mundo abierto desarrollado por la compañía británica Rockstar North y distribuido por Rockstar Games. Fue lanzado el 17 de septiembre de 2013 para las consolas PlayStation 3 y Xbox 360. Fecha de estreno inicial: 17 de septiembre de 2013. Creador(es): Dan Houser. Modos de juego: Un jugador y multijugador(en línea). Serie: Grand Theft Auto. Premios: Spike Video Game Award al Mejor Juego del Año. Diseñadores: Leslie Benzies, Imran Sarwar", "comprar":"comprar_juegos/"},' +
                        '{"titulo":"RESIDENT EVIL 7", "imagen":"covers_juegos/accion/residentevil7.jpg", "title":"Imagen-de-Resident-Evil-7", "fondo":"img3", "descripcion":"Resident Evil (estilizado como BIOHA7ARD) es un videojuego perteneciente al género del survival horror, desarrollado por la empresa japonesa Capcom, lanzado el 24 de Enero de 2017 para Microsoft Windows, PlayStation 4 y Xbox One, con una versión de PlayStation 4 con soporte completo para el PlayStation VR. Es el undécimo título de la serie principal de Resident Evil, y, a diferencia de la mayoría de los otros juegos de la franquicia, es en primera persona, siendo el primero de la saga principal en primera persona. Fecha de estreno inicial: 24 de enero de 2017. Motor: RE Engine. Modos de juego: Un jugador. Productor(es): Masachika Kawata. Plataformas: PlayStation 4, Xbox One, Nintendo Switch, Microsoft Windows. Premios: The Game Award for Best VR Game.", "comprar":"comprar_juegos/"},' +
                        '{"titulo":"THE LAST OF US", "imagen":"covers_juegos/accion/thelastofus.jpg", "title":"Imagen-de-The-Last-Of-Us", "fondo":"img4", "descripcion":"The Last of Us es un videojuego de acci\u00f3n-aventura y supervivencia de terror desarrollado por Naughty Dog, lanzado por Sony Computer Entertainment y estrenado mundialmente el 14 de junio de 2013 para PlayStation 3. Productor(es): Neil Druckmann. Motor: Havok. Modos de juego: Un jugador; Multijugador. Desarrollador: Naughty Dog. Plataformas: PlayStation 4, PlayStation 3.", "comprar":"comprar_juegos/"},' +
                        '{"titulo":"SHADOW OF THE TOMB RAIDER", "imagen":"covers_juegos/accion/tombraider.jpg", "title":"Imagen-de-Shadow-Of-The-Tomb-Raider", "fondo":"img5", "descripcion":"Shadow of the Tomb Raider es el pr\u00f3ximo videojuego de acci\u00f3n y aventura desarrollado por Eidos Montr\u00e9al y distribuido por Square Enix, para las plataformas PlayStation 4, Xbox One y Microsoft Windows. Fecha de estreno inicial: 14 de septiembre de 2018. Modos de juego: Un jugador. Distribuidor: Square Enix. Dise\u00f1ador: Heath Smith. G\u00e9nero: Videojuego de acci\u00f3n-aventura. Plataformas: PlayStation 4, Xbox One, Microsoft Windows. Desarrolladores: Crystal Dynamics, Eidos Montr\u00e9al.", "comprar":"comprar_juegos/"}]';     

var infojuegosaventura = '[{"titulo":"ASSASSIN´S CREED ORIGINS", "imagen":"covers_juegos/aventura/assassins6.jpg", "fondo":"img6", "descripcion":"Assassin´s Creed: Origins es un videojuego de acción - aventura y RPG de la saga Assassin´s Creed cuya fecha de lanzamiento fue el 27 de octubre de 2017. Está disponible para las plataformas PlayStation 4, Xbox One y PC. Fecha de estreno inicial: 27 de octubre de 2017. Modos de juego: Un jugador.  Motor: AnvilNext 2.0. Desarrollador: Ubisoft Montreal. Título original: Assassin´s Creed: Origins.Plataformas: PlayStation 4, Xbox One, Microsoft Windows. Géneros: Videojuego de acción-aventura, Videojuego de sigilo.", "comprar":"comprar_juegos/"},' +
                          '{"titulo":"GOD OF WAR 4", "imagen":"covers_juegos/aventura/godofwar4.jpg", "fondo":"img7", "descripcion":"God of War es un videojuego de acción-aventura desarrollado por SCE Santa Monica Studio y publicado por Sony Interactive Entertainment. Su lanzamiento se produjo el 20 de abril de 2018, en exclusiva para la consola PlayStation 4. Fecha de estreno inicial: 20 de abril de 2018. Modos de juego: Un jugador. Desarrollador: SCE Santa Monica Studio. Director(es): Cory Barlog. Serie: God of War. Plataforma: PlayStation 4.", "comprar":"comprar_juegos/"},' +
                          '{"titulo":"SHADOW OF THE COLOSSUSS", "imagen":"covers_juegos/aventura/shadowofthecolossus.jpg", "fondo":"img8", "descripcion":"Shadow of the Colossus es un videojuego de acción-aventura desarrollado y publicado por Sony Computer Entertainment para PlayStation 2. El juego fue publicado en Norteamérica y Japón en octubre de 2005, y posteriormente en Europa en febrero de 2006. Modos de juego: Un jugador. Productor(es): Kenji Kaido. Director(es): Fumito Ueda (director); Kenji Kaido (gestor de proyecto, productor). Diseñadores: Fumito Ueda, Kō Ōtani. Desarrolladores: Team ICO, Sony Interactive Entertainment, SIE Japan Studio. Plataformas: PlayStation 4, PlayStation 2, PlayStation 3.", "comprar":"comprar_juegos/"},' +
                          '{"titulo":"UNCHARTED 4", "imagen":"covers_juegos/aventura/uncharted4.jpg", "fondo":"img9", "descripcion":"Uncharted 4: El desenlace del ladrón, es un videojuego de acción-aventura en tercera persona, lanzado el 10 de mayo de 2016, distribuido por Sony Computer Entertainment y desarrollado Naughty Dog exclusivamente para PlayStation 4. Fecha de estreno inicial: 10 de mayo de 2016. Modos de juego: Un jugador; Multijugador. Desarrollador: Naughty Dog. Premios: The Game Award for Best Narrative, MÁS. Plataforma: PlayStation 4.  Diseñadores: Kurt Margenau, Robert Cogburn, Ricky Cambier, Emilia Schatz, Anthony Newman.", "comprar":"comprar_juegos/"},' +
                          '{"titulo":"WATCH DOGS 2", "imagen":"covers_juegos/aventura/watchdogs2.jpg", "fondo":"img10", "descripcion":"Watch Dogs 2 es un videojuego de mundo abierto y acción-aventura desarrollado por Ubisoft Montreal y distribuido por Ubisoft para las plataformas Microsoft Windows, PlayStation 4 y Xbox One. Es la secuela de Watch Dogs que fue lanzado a la venta el 15 de noviembre de 2016. Modos de juego: Un jugador; Multijugador. Género: Videojuego de acción-aventura. Director(es): Jonathan Morin; Danny Bélanger. Plataformas: PlayStation 4, Xbox One, Microsoft Windows. Desarrolladores: Ubisoft, Ubisoft Montreal, Ubisoft Reflections, Ubisoft Kiev, Ubisoft Paris, Ubisoft Bucharest, Ubisoft Toronto.", "comprar":"comprar_juegos/"}]'; 

var infojuegoscarreras = '[{"titulo":"DIRT 4", "imagen":"covers_juegos/carreras/dirt4.jpeg", "fondo":"img11", "descripcion":"Dirt 4, estetizado como DiRT 4, es un videojuego de carreras de rally desarrollado y publicado por Codemasters. Es el duodécimo juego en la serie de Rally de Colin McRae y el sexto título para llevar el nombre de Dirt. El juego fue lanzado en Microsoft Windows, PlayStation 4 y Xbox One el 9 de junio de 2017. Fecha de estreno inicial: 6 de junio de 2017. Desarrollador: Codemasters.Género: Videojuego de carreras. Motor: EGO. Serie: Colin McRae Rally. Plataformas: PlayStation 4, Xbox One, Microsoft Windows.", "comprar":"comprar_juegos/"},' +
                          '{"titulo":"GRAN TURISMO SPORT", "imagen":"covers_juegos/carreras/granturismo.jpg", "fondo":"img12", "descripcion":"Gran Turismo Sport es un videojuego de carreras desarrollado por Polyphony Digital y publicado por Sony Interactive Entertainment para la consola de videojuegos PlayStation 4. Fecha de estreno inicial: 17 de octubre de 2017. Modos de juego: Un jugador, Multijugador. Distribuidor: Sony Interactive Entertainment. Desarrollador: Polyphony Digital. Diseñador: Kazunori Yamauchi. Plataforma: PlayStation 4.", "comprar":"comprar_juegos/"},' +
                          '{"titulo":"MOTO GP 15", "imagen":"covers_juegos/carreras/motogp.jpg", "fondo":"img13", "descripcion":"MotoGP 15 es un videojuego desarrollado por Milestone Srl. El juego fue lanzado para Microsoft Windows, PlayStation 3, PlayStation 4, Xbox 360 y Xbox One el 24 de junio de 2015. Es el primero en ser lanzado en Xbox One y la última entrega para PlayStation 3 y Xbox 360. Fecha de estreno inicial: 24 de junio de 2015. Desarrollador: Milestone S.r.l. Serie: MotoGP. Distribuidor: Milestone S.r.l. Género: Videojuego de carreras. Plataformas: PlayStation 4, PlayStation 3, Xbox 360, Xbox One, Microsoft Windows, PlayStation Vita.", "comprar":"comprar_juegos/"},' +
                          '{"titulo":"NEED FOR SPEED PAYBACK", "imagen":"covers_juegos/carreras/needforspeedpayback.jpg", "fondo":"img14", "descripcion":"Need for Speed Payback es un videojuego de carreras de mundo abierto desarrollado por Ghost Games y distribuido por Electronic Arts para PlayStation 4, Xbox One y Microsoft Windows. Es la vigésima tercera entrega de la serie Need for Speed. Fecha de estreno inicial: 10 de noviembre de 2017. Modos de juego: Un jugador; Multijugador. Desarrollador: Ghost Games. Motor: Frostbite 3. Diseñador: Riley Cooper. Distribuidor: Electronic Arts. Plataformas: PlayStation 4, Xbox One, Microsoft Windows.", "comprar":"comprar_juegos/"},' +
                          '{"titulo":"PROjECT CARS 2", "imagen":"covers_juegos/carreras/projectcars2.jpg", "fondo":"img15", "descripcion":"Project CARS 2 es un videojuego simulador de carreras desarrollado por Slightly Mad Studios y publicado por Bandai Namco Entertainment, siendo la secuela del videojuego Project CARS de 2015. Su lanzamiento fue en septiembre de 2017, en Microsoft Windows, PlayStation 4 y Xbox One. Fecha de estreno inicial: 22 de septiembre de 2017. Modos de juego: Un jugador, multijugador. Desarrollador: Slightly Mad Studios. Género: Automovilismo virtual. Plataformas: PlayStation 4, Xbox One, Microsoft Windows. Distribuidores: Bandai Namco Entertainment, Bandai.", "comprar":"comprar_juegos/"}]'; 

var infojuegosdeportes = '[{"titulo":"FIFA 18", "imagen":"covers_juegos/deportes/fifa2018.jpg", "fondo":"img16", "descripcion":"FIFA 18 es un videojuego de fútbol, desarrollado por Electronic Arts y publicado por EA Sports Canadá y EA Sports Rumania. Es el 25.º de la serie de videojuegos de la FIFA. Salió a la venta el 29 de septiembre de 2017, siendo la portada del mismo Cristiano Ronaldo. Fecha de estreno inicial: 29 de septiembre de 2017. Modos de juego: Un jugador; Multijugador. Licencia: FIFpro. Plataformas: PlayStation 4, Android, Nintendo Switch, PlayStation 3, Xbox One, Xbox 360, Microsoft Windows. Distribuidores: Electronic Arts, EA Sports. Desarrolladores: Electronic Arts, EA Sports, EA Canada.", "comprar":"comprar_juegos/"},' +
                          '{"titulo":"FORMULA 1 2018", "imagen":"covers_juegos/deportes/formula12018.jpg", "fondo":"img17", "descripcion":"F1 2018 es un videojuego de carreras desarrollado y publicado por Codemasters. Está basado en la temporada 2018 de Fórmula 1, e incluye todos sus circuitos, equipos y pilotos. Fue lanzado el 24 de agosto de 2018 en Microsoft Windows, PlayStation 4, Xbox One, Android y iOS. Fecha de estreno inicial: 24 de agosto de 2018. Motor: EGO. Desarrollador: Codemasters. Distribuidor: Codemasters. Serie: Videojuegos de Fórmula 1. Género: Videojuego de carreras. Plataformas: PlayStation 4, Xbox One, Android, iOS, Microsoft Windows.", "comprar":"comprar_juegos/"},' +
                          '{"titulo":"NBA 2018", "imagen":"covers_juegos/deportes/nba2018.jpg", "fondo":"img18", "descripcion":"NBA 2K18 es un videojuego de simulación de baloncesto desarrollado por Visual Concepts y publicado por 2K Sports. Es la 19ª entrega de la franquicia NBA 2K y el sucesor de la NBA 2K17. Fecha de estreno inicial: 15 de septiembre de 2017. Desarrollador: Visual Concepts. Serie: NBA 2K. Plataformas: PlayStation 4, Android, Xbox One, Nintendo Switch, Xbox 360, PlayStation 3, Microsoft Windows. Distribuidores: 2K Games, 2K Sports. Géneros: Videojuego de deportes, Videojuego de simulación. Nominaciones: The Game Award al Mejor Juego Deportivo/Carreras.Nominaciones: The Game Award al Mejor Juego Deportivo/Carreras.Nominaciones: The Game Award al Mejor Juego Deportivo/Carreras.", "comprar":"comprar_juegos/"},' +
                          '{"titulo":"PES 2018", "imagen":"covers_juegos/deportes/pes2018.jpg", "fondo":"img19", "descripcion":"Pro Evolution Soccer 2018 es un videojuego de fútbol de la serie Pro Evolution Soccer desarrollado y publicado por Konami. Fecha de estreno inicial: 12 de septiembre de 2017. Fecha de estreno inicial: 12 de septiembre de 2017. Modos de juego: Un jugador; Multijugador. Controles: DualShock; Xbox 360 Controller; Ratón y teclado. Formato(s): Steam. Distribuidores: Konami, Konami Digital Entertainment. Plataformas: PlayStation 4, Android, PlayStation 3, Microsoft Windows, Xbox 360, Xbox One, iOS.Desarrolladores: Konami, Konami Digital Entertainment, PES Productions.", "comprar":"comprar_juegos/"},' +
                          '{"titulo":"AO TENNIS 2018", "imagen":"covers_juegos/deportes/tenis2018.jpg", "fondo":"img20", "descripcion":"AO Tennis is a tennis video game developed and published by Big Ant Studios. AO Tennis was released for PlayStation 4, Xbox One, Android and iOS on January 5, 2018. It is the first official licensed game of the Australian Open. It features a career mode where the player works to become world No. #1, starting by being world No. #1500. Desarrolladores: Big Ant Studios. Plataformas: PlayStation 4, Xbox One, iOS, Android, Microsoft Windows. Fechas de estreno inicial: iOS, Android: 5 January 2018, PlayStation 4, Xbox One: 16 January 2018, PC: 8 May 2018. Generos: Deportes.", "comprar":"comprar_juegos/"}]';

var infojuegosrpg = '[{"titulo":"BLOODBORNE", "imagen":"covers_juegos/rpg/bloodborne.jpg", "fondo":"img21", "descripcion":"Bloodborne es un videojuego de rol de acción dirigido por Hidetaka Miyazaki, desarrollado por From Software y distribuido por Sony Computer Entertainment para la plataforma de PlayStation 4. Compositor(es): Ryan Amon; Tsukasa Saitoh; Michael Wandmacher; Yuka Kitamura; Cris Velasco; Nobuyoshi Suzuki. Productor(es): Teruyuki Toriyama. Modos de juego: Un jugador, multijugador. Desarrollador: From Software. Diseñador: Hidetaka Miyazaki. Plataforma: PlayStation 4.", "comprar":"comprar_juegos/"},' +
                     '{"titulo":"DESTINY", "imagen":"covers_juegos/rpg/destiny.jpg", "fondo":"img22", "descripcion":"Destiny es un videojuego de disparos en primera persona, en forma de multijugador masivo en línea en un mundo abierto de ficción especulativa. Fue desarrollado por Bungie y publicado por Activision como parte de un contrato de producción de diez años. Compositor(es): Martin O´Donnell; Michael Salvatori; Paul McCartney; C Paul Johnson.Motor: In - house engine; Umbra 3. Productor(es): Bungie.Modos de juego: Un jugador, multijugador.Desarrolladores: Bungie Studios, High Moon Studios, Radical Entertainment.Plataformas: PlayStation 4, Xbox One, PlayStation 3, Xbox 360.", "comprar":"comprar_juegos/"},' +
                     '{"titulo":"FINAL FANTASY XV", "imagen":"covers_juegos/rpg/finalfantasy.jpg", "fondo":"img23", "descripcion":"Final Fantasy XV es un videojuego del género ARPG desarrollado por Square Enix, para PlayStation 4, Xbox One y Microsoft Windows. Junto con Final Fantasy XIII, Final Fantasy XIII-2, Final Fantasy Type-0 y Lightning Returns: Final Fantasy XIII, forma parte del proyecto Fabula Nova Crystallis: Final Fantasy. Clasificación(es): PEGI.Productor(es): Shinji Hashimoto. Compositora: Yōko Shimomura. Motor: Luminous Studio. Diseñadores: Tetsuya Nomura, Wan Hazmer. Plataformas: PlayStation 4, Xbox One, Microsoft Windows.", "comprar":"comprar_juegos/"},' +
                     '{"titulo":"HORIZON ZERO DAWN", "imagen":"covers_juegos/rpg/horizon.jpg", "fondo":"img24", "descripcion":"Horizon Zero Dawn es un videojuego de acción, aventura y de mundo abierto desarrollado por Guerrilla Games y distribuido por Sony Interactive Entertainment, únicamente para PlayStation 4. Productor(es): Lambert Wolterbeek Muller; Samrat Sharma. Compositor(es): Joris de Man; The Flight; Niels van der Leest; Jonathan Williams. Modos de juego: Un jugador. Desarrollador: Guerrilla Games. Motor: Decima. Premios: Golden Calf for Best Interactive.", "comprar":"comprar_juegos/"},' +
                     '{"titulo":"MONSTER HUNTER WORLD", "imagen":"covers_juegos/rpg/monsterhunter.jpg", "fondo":"img25", "descripcion":"Monster Hunter: World es un videojuego perteneciente al género de rol y acción, desarrollado y publicado por la empresa Capcom, siendo el sexto título principal de la franquicia de videojuegos Monster Hunter. El juego fue anunciado en la conferencia de Sony en la E3 2017. Fecha de estreno inicial: 26 de enero de 2018. Desarrollador: Capcom. Género: Videojuego de rol de acción. Motor: MT Framework. Distribuidor: Capcom. Plataformas: PlayStation 4, Xbox One, Microsoft Windows. Nominaciones: The Game Award al Juego Más Anticipado.", "comprar":"comprar_juegos/"}]';

var infojuegosshooters = '[{"titulo":"BATTLEFIELD 4", "imagen":"covers_juegos/shooters/battlefield4.jpg", "fondo":"img26", "descripcion":"Battlefield 4 fue desarrollado por la compañía EA Digital Illusions CE y distribuido por Electronic Arts para Microsoft Windows, Xbox 360, Xbox One, PlayStation 3 y PlayStation 4. Es la decimotercera entrega de la serie Battlefield y el sucesor del aclamado juego de 2011, Battlefield 3. Fecha de estreno inicial: 29 de octubre de 2013. Compositor(es): Johan Skugge; Jukka Rintamäki. Modos de juego: Un jugador, multijugador en línea. Motor: Frostbite. Plataformas: PlayStation 4, Xbox One, PlayStation 3, Xbox 360, Microsoft Windows. Premios: Premio Satellite al Mejor Juego de Acción/Aventuras.", "comprar":"comprar_juegos/"},' +
                          '{"titulo":"BATTLEFIELD HARDLINE", "imagen":"covers_juegos/shooters/battlefieldhardline.jpg", "fondo":"img27", "descripcion":"Battlefield Hardline es un videojuego de acción en primera persona lanzado el 18 de marzo de 2015, desarrollado por Visceral Games y EA Digital Illusions CE, y distribuido por Electronic Arts. Fecha de estreno inicial: 17 de marzo de 2015. Modos de juego: Un jugador; Multijugador. Distribuidor: Electronic Arts. Diseñador: Visceral Games. Desarrolladores: EA Digital Illusions CE, Visceral Games, Criterion Games. Plataformas: PlayStation 4, Xbox One, PlayStation 3, Xbox 360, Microsoft Windows.", "comprar":"comprar_juegos/"},' +
                          '{"titulo":"CALL OF DUTY BLACK OPS III", "imagen":"covers_juegos/shooters/callofdutybo3.jpeg", "fondo":"img28", "descripcion":"Call of Duty: Black Ops III es un videojuego de disparos en primera persona desarrollado por Treyarch, Beenox y Mercenary Technology, publicado por Activision. Es la 12° entrega de la saga Call of Duty y la secuela del videojuego de 2012 Call of Duty: Black Ops 2. Fue lanzado el 6 de noviembre de 2015. Fecha de estreno inicial: 6 de noviembre de 2015. Diseñador: Gavin Locke. Motor: IW engine. Plataformas: PlayStation 4, Xbox One, PlayStation 3, Xbox 360, Microsoft Windows. Clasificación: Mature. Desarrolladores: Treyarch, Beenox, Raven Software, Mercenary Technology.", "comprar":"comprar_juegos/"},' +
                          '{"titulo":"CALL OF DUTY WWII", "imagen":"covers_juegos/shooters/callofdutyww2.jpg", "fondo":"img29", "descripcion":"Call of Duty: WWII es un videojuego de disparos en primera persona desarrollado por Sledgehammer Games, distribuido por Activision, perteneciente a la franquicia Call of Duty. Es la décimo cuarta entrega numérica dentro de la misma saga, basada en la Segunda Guerra Mundial, después de Call of Duty: World at War. Fecha de estreno inicial: 3 de noviembre de 2017. Modos de juego: Un jugador; Multijugador; zombis. Distribuidor: Activision. Director(es): Bret Robbins; Dennis Adams. Desarrolladores: Sledgehammer Games, Raven Software. Plataformas: PlayStation 4, Xbox One, Microsoft Windows. Diseñadores: Glen Schofield, Michael Condrey.", "comprar":"comprar_juegos/"},' +
                          '{"titulo":"TOM CLANCY´S: RAINBOW SIX SIEGE", "imagen":"covers_juegos/shooters/rainbowsix.jpg", "fondo":"img30", "descripcion":"Tom Clancy´s Rainbow Six: Siege es un videojuego de disparos en primera persona táctico multijugador, desarrollado por la empresa Ubisoft Montreal y distribuido por Ubisoft para las plataformas PlayStation 4, Xbox One y Microsoft Windows.Fecha de estreno inicial: 1 de diciembre de 2015. Modos de juego: Un jugador; Multijugador. Motor: Anvil. Desarrolladores: Ubisoft Montreal, Ubisoft Kiev, Ubisoft Shanghai, Ubisoft Toronto, Ubisoft Barcelona, Ubisoft Chengdu. Plataformas: PlayStation 4, Xbox One, Microsoft Windows. Diseñadores: Andrew Witts, Daniel Drapeau, Chris Lee.", "comprar":"comprar_juegos/"}]';









